apiVersion: v1
kind: Namespace
metadata:
  name: webapp
---
apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
  namespace: webapp
type: Opaque
data:
  username: ZGJ1c2Vy
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: simple-webapp
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [webapp]}
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: sharma17393/simple-webapp:v1
          name: webfrontend
          env:
            - name:  MYSQL_HOST
              value:  "127.0.0.1"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: password
            - name: MYSQL_DATABASE
              value: employees
        - image: genschsa/mysql-employees:latest
          name: dbbackend
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: password
          # readinessProbe:
          #   exec:
          #     command: ["mysql", "-u", "root", "-p $(MYSQL_ROOT_PASSWORD)","-e", "SELECT 1"]
          #   initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webapp
  namespace: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
  - name:  http
    port:  8081
    nodePort: 30327